name: resource_network_fetcher
description: Uses the NetworkBoundResources to control the offline-first or only to centralize the errors from fetching from the network or any other function.
version: 2.0.0
homepage: https://polazzo.dev/
repository: https://github.com/LucazzP/resource_network_fetcher
issue_tracker: https://github.com/LucazzP/resource_network_fetcher/issues

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: any
  flutter_test:
    sdk: flutter
